# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

 source 'https://github.com/CocoaPods/Specs'
 source 'https://github.com/twilio/cocoapod-specs'
 
    
 target 'Spank' do
     pod 'TwilioChatClient', '~> 1.0.2'
     pod 'TwilioAccessManager', '~> 0.1.3'
     pod 'SlackTextViewController', '~> 1.9'

end
